busy_badger/busy_badger/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url( r"^polls/", include( "polls.urls", namespace="polls" ) ),
    url( r'^admin/', include( admin.site.urls ) ),
]

busy_badger/polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url( r"^$", views.XIndexView.as_view(), name="index" ),
    url( r"^(?P<pk>[0-9]+)/$", views.XDetailView.as_view(), name="details" ),
    url( r"^(?P<pk>[0-9]+)/res/$", views.XResultsView.as_view(), name="results" ),
    url( r"^(?P<question_id>[0-9]+)/vote/$", views.vote, name="vote" ),
]

busy_badger/polls/models.py
from django.db import models

class XQuestion( models.Model ):
    question_text = models.CharField( max_length=200 )
    pub_date = models.DateTimeField( "date published", auto_now_add=True )

    def __str__( self ):
        return self.question_text

class XChoice( models.Model ):
    question = models.ForeignKey( XQuestion )
    choice_text = models.CharField( max_length=200 )
    votes = models.IntegerField( default=0 )

    def __str__( self ):
        return self.choice_text

busy_badger/polls/views.py
from django.shortcuts           import render, get_object_or_404
from django.http                import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers   import reverse
from django.views               import generic

from .models                    import XQuestion, XChoice


class XIndexView( generic.ListView ):
    template_name       = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset( self ):
        return XQuestion.objects.order_by( "-pub_date" )[ :10 ]


class XDetailView( generic.DetailView ):
    model           = XQuestion
    template_name   = "polls/detail.html"


class XResultsView( generic.DetailView ):
    model           = XQuestion
    template_name   = "polls/results.html"


def vote( request, question_id ):
    p = get_object_or_404( XQuestion, pk=question_id )
    try:
        selected_choice = p.xchoice_set.get( pk=request.POST[ "choice" ] )
    except ( KeyError, XChoice.DoesNotExist ):
        cont = {
            "question": p,
            "error_message": "You didn't select a choice.",
        }
        return render( request, "polls/detail.html", cont )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect( reverse( "polls:results", args=( p.id, ) ) )

busy_badger/polls/templates/polls/detail.html
<h1> {{ xquestion.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' xquestion.id %}" method="post">
{% csrf_token %}
{% for choice in xquestion.xchoice_set.all %}
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"> <br>
{% endfor %}
<input type="submit" value="Vote">
</form>

busy_badger/polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
        <p>Posted on {{ question.pub_date }}</p>
    {% endfor %}
    </ul>

{% else %}
    <p>No polls are available.</p>
{% endif %}

busy_badger/polls/templates/polls/results.html
<h1>{{ xquestion.question_text }}</h1>

<ul>
    {% for choice in xquestion.xchoice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>        
    {% endfor %}
</ul>